apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/backend:latest
        ports:
        - containerPort: 5000