apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:15
          command: ["sh", "-c"]
          args:
            - |
              PGPASSWORD=$PGPASSWORD psql \
                -h postgres-service \
                -U admin \
                -d ecommerce \
                -c "CREATE TABLE IF NOT EXISTS users (
                      id SERIAL PRIMARY KEY,
                      name VARCHAR(100) NOT NULL,
                      email VARCHAR(100) UNIQUE NOT NULL,
                      password VARCHAR(200) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );"
          env:
            - name: PGPASSWORD
              value: admin
      restartPolicy: OnFailure
