apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: santosh-718/ecommerce-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: ecommerce_user
            - name: DB_PASSWORD
              value: strongpassword
            - name: DB_NAME
              value: ecommerce
